runtime: java11
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 0
  max_instances: 2
  min_pending_latency: 50ms
  max_pending_latency: automatic
  max_concurrent_requests: 5
